apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: server-ns
  name: ingress-server
spec:
  rules:
    - host: "www.staging-k8s-treggo.com" 
      http:
        paths:
          - backend:
              serviceName: server
              servicePort: 80
