apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: www.staging-k8s-treggo.com
      http:
        paths:
          - backend:
              serviceName: server
              servicePort: 80
